[package]
name = "declutter"
version = "0.1.0"
authors = ["Aman Kumar <akumar@gnome.org>"]
edition = "2021"

[lib]
name = "libdeclutter"
path = "src/lib.rs"

[dependencies]
adw = { version = "0.3.1", package = "libadwaita" }
anyhow = "1.0.70"
delegate = "0.9.0"
easy-ext = "1.0.1"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
glob = "0.3.1"
gtk = { version = "0.6", package = "gtk4" }
log = "0.4"
num-derive = "0.3.3"
num-traits = "0.2.15"
once_cell = "1.14"
paste = "1.0.12"
pretty_env_logger = "0.4"
regex = "1.8.1"
serde = "1.0.158"
serde_json = "1.0.94"
tempfile = "3.5.0"
tracker = { version = "0.4.0", package = "tracker-rs" }

[dependencies.strum]
version = "0.24.1"
features = ["derive"]

[build-dependencies.glob]
version = "0.3.1"
